services:
  soso-scheduler-service:
    container_name: soso-scheduler
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - soso_scheduler_network

networks:
  soso_scheduler_network:
    driver: bridge
